version: '2'
services:
  api:
    build: ./DeliverGames-api/
    volumes:
      - ./DeliverGames-api/:/app/
      - /app/node_modules
    command: npm start
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongodata:/data/db
    ports:
        - 27017:27017
volumes:
  mongodata:
