version: '2'
services:
  api:
    build: ./DeliverGames-api/
    volumes:
      - ./DeliverGames-api/:/api/
      - /api/node_modules
    command: npm start
    ports:
      - "8000:8000"
    network_mode: "host"
